#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app     = new Symfony\Component\Console\Application('Hitgo command line tool');
$default_command = new Hitgo\Installer\Console\DeployCommand();

$app->add($default_command);
$app->setDefaultCommand($default_command->getName());

$app->run();
