#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$command     = new Hitgo\Installer\Console\DeployCommand();
$application = new Symfony\Component\Console\Application('Hitgo command line tool', '0.1.0');

$application->add($command);
$application->setDefaultCommand($command->getName());

$application->run();
